version: '3'

services:
  app:
    image: luistasayco2004/traductor:v1.0
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_API_KEY: ${DATABASE_API_KEY}